window.myersFigures = {
  unit0: [
    { source:"Myers", src:"assets/myers/correlation-scatterplots.jpg", page:83, figure:"Figures 6.1–6.2", title:"Correlation scatterplots", concepts:["scatterplot","correlation coefficient","positive correlation","negative correlation"], alt:"Myers scatterplots comparing positive and negative correlations", caption:"Compare direction and strength by reading the slope and closeness of the plotted points.", scope:"A correlation describes an association; it does not by itself show causation." },
    { source:"Myers", src:"assets/myers/skewed-distribution-outliers.jpg", page:101, figure:"Textbook diagram", title:"Skewed distributions and outliers", concepts:["mean","median","skewed distribution","outlier"], alt:"Myers diagram showing how an extreme score changes the mean of a distribution", caption:"Notice that an extreme score pulls the mean farther than the median.", scope:"Use the median when a skewed distribution makes the mean unrepresentative." },
    { source:"Myers", src:"assets/myers/normal-distribution.jpg", page:102, figure:"Textbook diagram", title:"Normal distribution and standard deviation", concepts:["normal distribution","standard deviation","percentile rank"], alt:"Myers normal curve labeled with standard-deviation intervals and percentages", caption:"Connect distance from the mean with the 68–95–99.7 pattern.", scope:"Interpret areas and spread; no inferential-test calculation is required." }
  ],
  "1.2": [
    { source:"Myers", src:"assets/myers/nervous-system-divisions.jpg", page:124, figure:"Figure 10.1", title:"Nervous-system divisions", concepts:["central nervous system","peripheral nervous system","cns","pns","somatic nervous system","autonomic nervous system","sympathetic nervous system","parasympathetic nervous system"], alt:"Myers hierarchy dividing the central and peripheral nervous systems into somatic and autonomic branches", caption:"Follow the hierarchy from CNS and PNS to the somatic and autonomic subdivisions.", scope:"Use the organization to compare voluntary control with sympathetic and parasympathetic regulation." },
    { source:"Myers", src:"assets/myers/autonomic-nervous-system.jpg", page:125, figure:"Figure 10.2", title:"Autonomic nervous-system functions", concepts:["autonomic nervous system","sympathetic nervous system","parasympathetic nervous system"], alt:"Myers body diagram comparing sympathetic arousal with parasympathetic calming effects", caption:"Compare paired sympathetic and parasympathetic effects on the same organs.", scope:"Relate the two branches to arousal, recovery, and homeostasis." },
    { source:"Myers", src:"assets/myers/reflex-pathway.jpg", page:127, figure:"Figure 10.3", title:"A simple reflex pathway", concepts:["sensory neurons","motor neurons","interneurons","reflex arc","spinal cord"], alt:"Myers diagram tracing a sensory neuron through the spinal cord to a motor neuron in a reflex", caption:"Trace sensory input to an interneuron and motor output before conscious brain processing.", scope:"Use the pathway to distinguish sensory, motor, and interneuron roles." }
  ],
  "1.3": [
    { source:"Myers", src:"assets/myers/neuron-structure.jpg", page:115, figure:"Figure 9.2", title:"Neuron structure", concepts:["neuron","neurons","dendrites","cell body","axon","myelin sheath","glial cells"], alt:"Myers neuron diagram labeling dendrites, cell body, axon, myelin sheath, and terminal branches", caption:"Trace neural information from dendrites through the cell body and axon to terminal branches.", scope:"Connect each major structure to receiving, integrating, or transmitting information." },
    { source:"Myers", src:"assets/myers/action-potential.jpg", page:117, figure:"Figure 9.4", title:"Action potential", concepts:["action potential","threshold","all-or-none response","refractory period","depolarization"], alt:"Myers graph and axon sequence showing depolarization and repolarization during an action potential", caption:"Follow the rapid voltage change once threshold is reached, followed by recovery.", scope:"Focus on threshold, all-or-none firing, and the refractory period rather than ion-pump detail." },
    { source:"Myers", src:"assets/myers/synapse-receptors.jpg", page:121, figure:"Textbook diagram", title:"Synapse and receptor action", concepts:["neurotransmitter","synapse","agonist","antagonist","reuptake","receptor sites"], alt:"Myers synapse diagrams showing neurotransmitter release and receptor activation or blocking", caption:"See how chemical messengers cross the synaptic gap and bind to receptor sites.", scope:"Use receptor fit to explain agonists, antagonists, and reuptake effects." }
  ],
  "1.4": [
    { source:"Myers", src:"assets/myers/brainstem-reticular-formation.jpg", page:135, figure:"Figure 11.4", title:"Brainstem and reticular formation", concepts:["brainstem","medulla","pons","reticular formation","thalamus"], alt:"Myers cutaway brain diagram labeling the brainstem, medulla, pons, thalamus, and reticular formation", caption:"Locate core brainstem structures and the reticular formation’s path through them.", scope:"Connect these structures to basic survival functions, sleep, and arousal." },
    { source:"Myers", src:"assets/myers/cerebellum.jpg", page:136, figure:"Textbook diagram", title:"Cerebellum and coordinated movement", concepts:["cerebellum"], alt:"Myers diagram locating the cerebellum and illustrating coordinated movement", caption:"Locate the cerebellum behind the brainstem and connect it to coordination and motor learning.", scope:"The cerebellum supports balance, movement, and nonverbal learning." },
    { source:"Myers", src:"assets/myers/brain-structures.jpg", page:139, figure:"Figure 11.11", title:"Major brain structures", concepts:["limbic system","hippocampus","amygdala","hypothalamus","thalamus","brainstem","cerebellum"], alt:"Myers cutaway brain overview labeling major limbic and lower-brain structures", caption:"Use the spatial overview to relate limbic, brainstem, and cerebellar structures.", scope:"Pair location with function and likely effects of damage." },
    { source:"Myers", src:"assets/myers/cortical-lobes.jpg", page:143, figure:"Figure 12.1", title:"Lobes of the cerebral cortex", concepts:["frontal lobe","prefrontal cortex","parietal lobe","temporal lobe","occipital lobe","cerebral cortex"], alt:"Myers lateral brain diagram distinguishing frontal, parietal, temporal, and occipital lobes", caption:"Use the color-coded map to connect each cortical lobe with its major functions.", scope:"Study functional regions and damage effects, not personality stereotypes about hemispheres." },
    { source:"Myers", src:"assets/myers/motor-somatosensory-cortex.jpg", page:144, figure:"Textbook diagram", title:"Motor and somatosensory cortex", concepts:["motor cortex","somatosensory cortex","frontal lobe","parietal lobe"], alt:"Myers cortical maps showing body areas represented in motor and somatosensory cortex", caption:"Notice that cortical space reflects control or sensitivity, not body-part size.", scope:"Distinguish the frontal-lobe motor strip from the parietal-lobe sensory strip." },
    { source:"Myers", src:"assets/myers/split-brain-pathway.jpg", page:154, figure:"Textbook diagram", title:"Split-brain visual pathway", concepts:["corpus callosum","split-brain","lateralization","left hemisphere","right hemisphere"], alt:"Myers split-brain diagram tracing visual-field input to the opposite cerebral hemisphere", caption:"Trace each visual field to the opposite hemisphere when the corpus callosum is severed.", scope:"Use the pathway to explain lateralized language and spatial responses without oversimplified left-brain/right-brain labels." }
  ],
  "1.5": [
    { source:"Myers", src:"assets/myers/sleep-recordings.jpg", page:266, figure:"Textbook diagram", title:"Sleep recordings and brain waves", concepts:["electroencephalogram","eeg","sleep stages","nrem","alpha waves","delta waves"], alt:"Myers sleep-lab recordings comparing eye movements, muscle tension, and brain waves", caption:"Compare the physiological recordings used to identify stages of sleep.", scope:"Recognize changing wave patterns and REM features; memorize only the CED-listed distinctions." },
    { source:"Myers", src:"assets/myers/sleep-cycle.jpg", page:267, figure:"Textbook diagram", title:"A typical night’s sleep cycle", concepts:["nrem stages 1-3","nrem","rem","sleep cycle","rem rebound"], alt:"Myers hypnogram showing repeated NREM and REM cycles across a night", caption:"Deep NREM dominates earlier cycles, while REM periods lengthen later in the night.", scope:"Use the graph to explain recurring stage sequences and changes across the night." }
  ],
  "1.6": [
    { source:"Myers", src:"assets/myers/eye-anatomy.jpg", page:211, figure:"Textbook diagram", title:"Eye anatomy and visual pathway", concepts:["eye","lens","retina","pupil","cornea","optic nerve","transduction"], alt:"Myers cross section of the eye labeling the cornea, pupil, lens, retina, and optic nerve", caption:"Trace light through the cornea, pupil, and lens to the retina and optic nerve.", scope:"Connect focusing and retinal transduction to neural signals sent toward visual cortex." },
    { source:"Myers", src:"assets/myers/retinal-layers.jpg", page:211, figure:"Textbook diagram", title:"Retinal processing layers", concepts:["retina","rods","cones","bipolar cells","ganglion cells","transduction"], alt:"Myers retinal-layer diagram showing rods, cones, bipolar cells, and ganglion cells", caption:"Follow information from rods and cones through bipolar and ganglion cells.", scope:"Use the pathway to explain visual transduction and why the optic nerve leaves the retina." },
    { source:"Myers", src:"assets/myers/ear-cochlea-pathway.jpg", page:233, figure:"Textbook diagram", title:"Ear and cochlear pathway", concepts:["ear","cochlea","hair cells","basilar membrane","auditory nerve","transduction","pitch"], alt:"Myers ear and cochlea diagrams tracing sound through the middle ear to hair cells and the auditory nerve", caption:"Trace sound vibrations into the cochlea, where hair-cell movement begins neural transduction.", scope:"Connect cochlear location and firing rate with pitch-processing explanations." }
  ],
  "2.1": [
    { source:"Myers", src:"assets/myers/perceptual-set.jpg", page:202, figure:"Textbook illusion", title:"Perceptual set", concepts:["perceptual sets","perceptual set","top-down processing"], alt:"Myers ambiguous figure that can be seen as either a young woman or an older woman", caption:"The same lines support different perceptions depending on expectation and prior experience.", scope:"Use the illusion to distinguish top-down interpretation from incoming sensory features." }
  ],
  "2.3": [
    { source:"Myers", src:"assets/myers/working-memory-model.jpg", page:363, figure:"Textbook model", title:"Working memory", concepts:["working memory model","working memory","central executive","phonological loop","visuospatial sketchpad"], alt:"Myers working-memory model connecting a central executive with verbal and visual-spatial processing", caption:"See how the central executive coordinates verbal and visual-spatial information.", scope:"Treat working memory as an active processing system with limited capacity." }
  ],
  "3.4": [
    { source:"Myers", src:"assets/myers/theory-of-mind.jpg", page:535, figure:"False-belief task", title:"Theory of mind", concepts:["theory of mind","false belief"], alt:"Myers sequence illustrating a child reasoning about another person’s false belief", caption:"The task asks where a character will search based on what that character knows.", scope:"Use success on false-belief tasks as evidence of developing perspective taking." }
  ],
  "3.7": [
    { source:"Myers", src:"assets/myers/classical-conditioning.jpg", page:307, figure:"Textbook sequence", title:"Classical conditioning", concepts:["classical conditioning","unconditioned stimulus","ucs","unconditioned response","ucr","conditioned stimulus","cs","conditioned response","cr","acquisition"], alt:"Myers dog-conditioning sequence showing food, salivation, a tone, and the learned response", caption:"Identify the stimulus-response pair before, during, and after acquisition.", scope:"Use the sequence for UCS, UCR, CS, CR, acquisition, extinction, recovery, generalization, and discrimination." }
  ],
  "3.8": [
    { source:"Myers", src:"assets/myers/reinforcement-schedules.jpg", page:321, figure:"Textbook graph", title:"Reinforcement schedule response patterns", concepts:["reinforcement schedules","fixed-ratio","variable-ratio","fixed-interval","variable-interval","partial reinforcement"], alt:"Myers response graphs comparing fixed and variable ratio and interval reinforcement schedules", caption:"Compare the high steady output of variable-ratio schedules with the pauses or scallops of fixed schedules.", scope:"Distinguish whether reinforcement depends on responses or time, and whether the requirement is fixed or variable." }
  ],
  "3.9": [
    { source:"Myers", src:"assets/myers/observational-learning.jpg", page:346, figure:"Bobo doll study", title:"Observational learning", concepts:["observational learning","modeling","vicarious reinforcement","Bandura","Bobo doll"], alt:"Myers photographs from Bandura’s Bobo doll research showing modeled aggression and child imitation", caption:"Children reproduced behavior they had observed in an adult model.", scope:"Use the study to explain modeling and the influence of observed consequences." }
  ],
  "4.5": [
    { source:"Myers", src:"assets/myers/reciprocal-determinism.jpg", page:639, figure:"Textbook model", title:"Reciprocal determinism", concepts:["reciprocal determinism","social-cognitive theory","behavior","environment","personal factors"], alt:"Myers triangle showing reciprocal influence among behavior, internal personal factors, and environmental factors", caption:"Each point of the triangle both affects and is affected by the other two.", scope:"Use the model to explain person-situation interaction in social-cognitive personality theory." }
  ],
  "4.6": [
    { source:"Myers", src:"assets/myers/yerkes-dodson-law.jpg", page:437, figure:"Textbook graph", title:"Yerkes-Dodson law", concepts:["yerkes-dodson law","yerkes-dodson","arousal","motivation"], alt:"Myers inverted-U graph relating arousal level to performance for tasks of differing difficulty", caption:"Performance is best at an intermediate arousal level, with the optimum varying by task difficulty.", scope:"Apply the pattern to performance; avoid assuming one ideal arousal level for every task." }
  ],
  "5.1": [
    { source:"Myers", src:"assets/myers/general-adaptation-syndrome.jpg", page:488, figure:"Textbook graph", title:"General adaptation syndrome", concepts:["general adaptation syndrome","general adaptation syndrome gas","alarm","resistance","exhaustion","stress"], alt:"Myers graph of Selye’s alarm, resistance, and exhaustion stages during prolonged stress", caption:"Follow the body’s resources through alarm, resistance, and eventual exhaustion.", scope:"Use the stages to explain physiological responses to sustained stress." }
  ]
};
